---
title: 'Comparing the exponential distribution in R with the Central Limit Theorem'
author: "Alexander Pyle, <apyle@github.com>"
date: "November 8, 2015"
output: 
  html_document:
    keep_md: true
---

 A sample set of headings that could be used to guide the creation of your report might be:

    Title (give an appropriate title) and Author Name
    Overview: In a few (2-3) sentences explain what is going to be reported on.
    Simulations: Include English explanations of the simulations you ran, with the accompanying R code. Your explanations should make clear what the R code accomplishes.
    Sample Mean versus Theoretical Mean: Include figures with titles. In the figures, highlight the means you are comparing. Include text that explains the figures and what is shown on them, and provides appropriate numbers.
    Sample Variance versus Theoretical Variance: Include figures (output from R) with titles. Highlight the variances you are comparing. Include text that explains your understanding of the differences of the variances.
    Distribution: Via figures and text, explain how one can tell the distribution is approximately normal. 
    

```{r}

lambda = 0.2    # given by assignment
samples = 40    # number of samples to use for the mean
simulations = 1000      # number of simulations to run

meanexp = NULL
for (i in 1 : simulations) 
        meanexp = c(meanexp, mean(rexp(samples, lambda)))
hist (meanexp)

# nosim <- 1000
# cfunc <- function(x, n) sqrt(n) * (mean(x) - 0.9) / sqrt(.1 * .9)
# dat <- data.frame(
#         x = c(apply(matrix(sample(0:1, prob = c(.1,.9), nosim * 10, replace = TRUE), 
#                            nosim), 1, cfunc, 10),
#               apply(matrix(sample(0:1, prob = c(.1,.9), nosim * 30, replace = TRUE), 
#                            nosim), 1, cfunc, 30),
#               apply(matrix(sample(0:1, prob = c(.1,.9), nosim * 50, replace = TRUE), 
#                            nosim), 1, cfunc, 50)
#         ),
#         size = factor(rep(c(10, 30, 50), rep(nosim, 3))))
# g <- ggplot(dat, aes(x = x, fill = size)) + geom_histogram(binwidth=.3, colour = "black", aes(y = ..density..)) 
# g <- g + stat_function(fun = dnorm, size = 2)
# g + facet_grid(. ~ size)

```

